osx_image: xcode8.3

os:
  - linux
  - osx

language: node_js
sudo: false
node_js:
  - 6

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-mac; fi
  - npm run test

cache:
  directories:
    - "node_modules"