os:
  - linux
  - osx

language: node_js
sudo: false
node_js:
  - node
  - lts/*
  - 6

jobs:
  include: 
    - stage: test
    - script: npm run test-all
    - stage: package
    - script: npm run package-all
